version: 2.1

orbs:
  general-platform-helpers: okta/general-platform-helpers@1.9
  node: circleci/node@7.0.0

executors:
  linux:
    machine:
      image: ubuntu-2404:current
    resource_class: xlarge

commands:
  install_android_sdk:
    description: "Install Android SDK in macOS machine"
    steps:
      - run: wget --quiet --output-document="$HOME/android-commandline.zip" https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
      - run: (cp .circleci/android_sdk_checksum $HOME/checksum; cd $HOME; shasum -a256 -c checksum)
      - run: set +o pipefail
      - run: unzip "$HOME/android-commandline.zip" -d "$HOME"
      - run: mkdir "$HOME/android-sdk"
      - run: echo y | $HOME/cmdline-tools/bin/sdkmanager --sdk_root="$HOME/android-sdk" "platforms;android-35" > /dev/null
      - run: echo y | $HOME/cmdline-tools/bin/sdkmanager --sdk_root="$HOME/android-sdk" "platform-tools" > /dev/null
      - run: echo y | $HOME/cmdline-tools/bin/sdkmanager --sdk_root="$HOME/android-sdk" "build-tools;35.0.0" > /dev/null
      - run: (yes || true) | $HOME/cmdline-tools/bin/sdkmanager --sdk_root="$HOME/android-sdk" --licenses
      - run: echo 'export ANDROID_HOME="$HOME/android-sdk"' >> "$BASH_ENV"
      - run: set -o pipefail

  setup:
    description: "Setup project for security scan"
    steps:
      - checkout
      - install_android_sdk
      - run: yarn install --frozen-lockfile
      - run: (cd browser-sign-in; yarn install --frozen-lockfile)
      - run: (cd browser-sign-in/android; ./gradlew assembleDebug) # Avoid gradle build during snyk scan
      - run: (cd custom-sign-in; yarn install --frozen-lockfile)
      - run: (cd custom-sign-in/android; ./gradlew assembleDebug) # Avoid gradle build during snyk scan

jobs:
  snyk-scan:
    executor: linux
    steps:
      - setup
      - run: pip install setuptools
      - general-platform-helpers/step-load-dependencies
      - general-platform-helpers/step-run-snyk-monitor:
          run-on-non-main: true
          scan-all-projects: true
          skip-unresolved: false

workflows:
  security-scan:
    jobs:
      - snyk-scan:
          name: execute-snyk
          context:
            - static-analysis
          filters:
           branches:
             only:
               - master